services:
  local-postgres:
    image: postgres
    container_name: postgres-caridadems
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "caridadedb"
    ports:
      - "5434:5432"
    networks:
      - postgres-compose-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  postgres-compose-network:
    driver: bridge

volumes:
  postgres-data:
