CREATE TABLE IF NOT EXISTS menu_campaign_donation (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  menu_campaign_id  INTEGER NOT NULL,
  donation_item_id  INTEGER NOT NULL,
  donor_id          INTEGER,
  donation_date     DATE,
  quantity          NUMERIC(19,3) NOT NULL,
  notes             VARCHAR(255),

  CONSTRAINT fk_mcd_menu_campaign_v2
    FOREIGN KEY (menu_campaign_id) REFERENCES menu_campaign_v2 (id) ON DELETE CASCADE,

  CONSTRAINT fk_mcd_donation_item
    FOREIGN KEY (donation_item_id) REFERENCES donation_item (id),

  CONSTRAINT fk_mcd_donor
    FOREIGN KEY (donor_id) REFERENCES donor (id)
);