create table address (
    id integer generated by default as identity,
    charity_group_id integer,
    city_id integer,
    donor_id integer,
    type_address smallint check (type_address between 0 and 2),
    cep varchar(255),
    complement varchar(255),
    number varchar(255),
    street varchar(255),
    primary key (id)
);

create table campaign (
    id integer generated by default as identity,
    charity_group_id integer,
    date_end date,
    date_init date,
    status smallint check (status between 0 and 2),
    description varchar(255),
    name varchar(255),
    primary key (id)
);

create table charity_group (
    id integer generated by default as identity,
    description varchar(255),
    email varchar(255),
    name varchar(255),
    phone varchar(255),
    primary key (id)
);

create table city (
    id integer generated by default as identity,
    state_id integer,
    name varchar(255),
    primary key (id)
);

create table donation_item (
    id integer generated by default as identity,
    menu_campaign_id integer,
    product_id integer unique,
    quantity double precision,
    status_item smallint check (status_item between 0 and 2),
    primary key (id)
);

create table donation_item_menu_campaign (
    id integer generated by default as identity,
    donation_date date,
    donation_item_id integer unique,
    donor_id integer,
    quantity double precision,
    primary key (id)
);

create table donor (
    id integer generated by default as identity,
    email varchar(255),
    name varchar(255),
    phone varchar(255),
    primary key (id)
);

create table menu_campaign (
    id integer generated by default as identity,
    campaign_id integer,
    meal_type varchar(255),
    primary key (id)
);

create table menu_campaign_donation_items (
    donation_items_id integer not null unique,
    menu_campaign_id integer not null
);

create table product (
    id integer generated by default as identity,
    product_category smallint check (product_category between 0 and 3),
    unit_of_measure smallint check (unit_of_measure between 0 and 3),
    name varchar(255),
    primary key (id)
);

create table state (
    id integer generated by default as identity,
    name varchar(255),
    sigla varchar(255),
    primary key (id)
);

-- Constraints

alter table address
    add constraint FK_address_charity_group foreign key (charity_group_id) references charity_group;

alter table address
    add constraint FK_address_city foreign key (city_id) references city;

alter table address
    add constraint FK_address_donor foreign key (donor_id) references donor;

alter table campaign
    add constraint FK_campaign_charity_group foreign key (charity_group_id) references charity_group;

alter table city
    add constraint FK_city_state foreign key (state_id) references state;

alter table donation_item
    add constraint FK_donation_item_menu_campaign foreign key (menu_campaign_id) references menu_campaign;

alter table donation_item
    add constraint FK_donation_item_product foreign key (product_id) references product;

alter table donation_item_menu_campaign
    add constraint FK_donation_item_menu_campaign_item foreign key (donation_item_id) references donation_item;

alter table donation_item_menu_campaign
    add constraint FK_donation_item_menu_campaign_donor foreign key (donor_id) references donor;

alter table menu_campaign
    add constraint FK_menu_campaign_campaign foreign key (campaign_id) references campaign;

alter table menu_campaign_donation_items
    add constraint FK_menu_campaign_donation_item foreign key (donation_items_id) references donation_item;

alter table menu_campaign_donation_items
    add constraint FK_menu_campaign_menu foreign key (menu_campaign_id) references menu_campaign;
