CREATE TABLE IF NOT EXISTS menu (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title        VARCHAR(255) NOT NULL,
  meal_type    smallint check (meal_type between 0 and 2)
);