CREATE TABLE IF NOT EXISTS menu_campaign_v2 (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id  INTEGER NOT NULL,
  menu_id      INTEGER NOT NULL,
  qty_planned  INTEGER,
  notes        VARCHAR(255),

  CONSTRAINT fk_menu_campaign_v2_campaign
    FOREIGN KEY (campaign_id) REFERENCES campaign (id),

  CONSTRAINT fk_menu_campaign_v2_menu
    FOREIGN KEY (menu_id) REFERENCES menu (id)
);