CREATE TABLE IF NOT EXISTS menu_campaign_item_need (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  menu_campaign_id  INTEGER NOT NULL,
  donation_item_id  INTEGER NOT NULL,
  amount_needed     NUMERIC(19,3) NOT NULL,

  CONSTRAINT fk_mc_need_menu_campaign_v2
    FOREIGN KEY (menu_campaign_id) REFERENCES menu_campaign_v2 (id) ON DELETE CASCADE,

  CONSTRAINT fk_mc_need_donation_item
    FOREIGN KEY (donation_item_id) REFERENCES donation_item (id)
);