name: Gerar Release e Pull Request para Main

on:
  push:
    branches:
      - develop

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout c처digo
        uses: actions/checkout@v4

      - name: Extrai vers찾o do pom.xml e remove -SNAPSHOT
        id: version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          CLEAN_VERSION=$(echo "$VERSION" | sed 's/-SNAPSHOT//')
          echo "version=${CLEAN_VERSION}" >> $GITHUB_OUTPUT

      - name: Cria release no GitHub
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          body: "Release gerada ap처s merge na develop"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cria PR da develop para main
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          source: develop
          base: main
          title: "Release: Merge develop into main"
          body: "Esta PR foi criada automaticamente ap처s merge na develop."
          branch: release/develop-to-main-${{ github.run_number }}
